@startuml ZooSimulation
title 動物園シミュレーション

ZooSimulation o-- NextAction
NextAction --> ZooOwner
ZooOwner o-- Zoo
ZooOwner o-- ZooOrganization
ZooOrganization --> AnimalTradeAgency
Zoo o-- Animal
AnimalTradeAgency o-- AnimalTrader
AnimalTrader o-- Animal

class ZooSimulation {
  + Run(): void
}

class NextAction {
  + ZooOwner: ZooOwner
  + ListNextActions(): {key[string]: ActionMethod}
  - IntroduceNewAnimal()
  - QuitGame()
  - CreateZooOwner(): ZooOwner
}

class ZooOwner {
  + Name: string
  + OwnZoo: Zoo
  + OwnZooOrganization: ZooOrganization
  + IntroduceAnimal()
  - ContractWithAnimalTrader()
  - BuyAnimal()
  - BreedAnimal()
  - TradeAnimal()
  - RescueAnimal()
}

class ZooOrganization {
  + ContractedAnimalTrader
  + ContractWithAnimalTrader()
}

class Zoo {
  + Name: string
  + Animals: Animal[]
  + ListAnimals(): void
}

class Animal {
  + Name: string
  + Price: int
  + Display(): void
}

class AnimalTrader {
  + Name: string
  + Animals: Animal[]
  + ListBuyableAnimals(): void
}
class AnimalTradeAgency {
  + AllAnimalTraders : AnimalTrader[]
  + ListAllAnimalTraders(): void
  + BrokerContractWithAnimalTrader()
}

@enduml
