Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - 'spec/models/value_object_spec.rb'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/knowledge/pricing_demand_spec.rb'
    - 'spec/knowledge/reputation_spec.rb'

Naming/MethodParameterName:
  Exclude:
    - 'spec/knowledge/metabolism_spec.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/models/animal.rb'
    - 'app/models/species.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/models/species_catalog.rb'
