# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bootsnap', require: false
gem 'graphql', '~> 2.6'
gem 'puma'
gem 'rack-cors'
gem 'rails', '~> 8.1.4'
gem 'sqlite3', '~> 2.9'

group :development, :test do
  gem 'debug', require: 'debug/prelude'
  gem 'rspec-rails', '~> 8.0'
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'simplecov', require: false
end
